name: factorio-calculator
version: 0.1.0.0
github: "githubuser/calculator"
license: MIT
author: "Jan Sipr"
maintainer: "sipr.jan@gmail.com"
copyright: "2018 Jan Sipr"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: >
  Please see the README on GitHub at
  <https://github.com/Siprj/factorio-calculator#readme>

dependencies:
  - base >= 4.7 && < 5
  - filepath
  - aeson
  - bytestring
  - containers
  - unordered-containers
  - directory
  - text
  - zip
  - extra
  - mtl
  - vector

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -static
    - -fPIC

executables:
  calculator:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -static
    dependencies:
      - factorio-calculator
      - optparse-applicative

tests:
  factorio-calculator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - factorio-calculator
